//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Areas.QmsIpqcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.webservice.spc.com", ConfigurationName="QmsIpqcService.putIpqcInspectDataFromMesPortType")]
    public interface putIpqcInspectDataFromMesPortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:putIpqcInspectDataFromMes", ReplyAction="urn:putIpqcInspectDataFromMesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesResponse putIpqcInspectDataFromMes(Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="putIpqcInspectDataFromMes", WrapperNamespace="http://impl.webservice.spc.com", IsWrapped=true)]
    public partial class putIpqcInspectDataFromMesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.webservice.spc.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string insDatas;
        
        public putIpqcInspectDataFromMesRequest() {
        }
        
        public putIpqcInspectDataFromMesRequest(string insDatas) {
            this.insDatas = insDatas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="putIpqcInspectDataFromMesResponse", WrapperNamespace="http://impl.webservice.spc.com", IsWrapped=true)]
    public partial class putIpqcInspectDataFromMesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.webservice.spc.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public putIpqcInspectDataFromMesResponse() {
        }
        
        public putIpqcInspectDataFromMesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface putIpqcInspectDataFromMesPortTypeChannel : Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class putIpqcInspectDataFromMesPortTypeClient : System.ServiceModel.ClientBase<Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesPortType>, Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesPortType {
        
        public putIpqcInspectDataFromMesPortTypeClient() {
        }
        
        public putIpqcInspectDataFromMesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public putIpqcInspectDataFromMesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public putIpqcInspectDataFromMesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public putIpqcInspectDataFromMesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesResponse Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesPortType.putIpqcInspectDataFromMes(Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesRequest request) {
            return base.Channel.putIpqcInspectDataFromMes(request);
        }
        
        public string putIpqcInspectDataFromMes(string insDatas) {
            Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesRequest inValue = new Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesRequest();
            inValue.insDatas = insDatas;
            Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesResponse retVal = ((Zephyr.Areas.QmsIpqcService.putIpqcInspectDataFromMesPortType)(this)).putIpqcInspectDataFromMes(inValue);
            return retVal.@return;
        }
    }
}
