//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Areas.ServiceReferenceAPS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAPS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GET_APS_DISPATCHResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_APS_DISPATCH", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse GET_APS_DISPATCH(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_APS_DISPATCH", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse> GET_APS_DISPATCHAsync(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GET_OVER_ORDERResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_OVER_ORDER", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse GET_OVER_ORDER(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_OVER_ORDER", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse> GET_OVER_ORDERAsync(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GET_APS_MATERIASETResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_APS_MATERIASET", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse GET_APS_MATERIASET(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_APS_MATERIASET", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse> GET_APS_MATERIASETAsync(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_materialResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_material", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse Get_material(Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_material", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse> Get_materialAsync(Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_lineResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_line", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse Get_line(Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_line", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse> Get_lineAsync(Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_technologyResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_technology", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse Get_technology(Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_technology", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse> Get_technologyAsync(Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GET_lineRproductResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_lineRproduct", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse GET_lineRproduct(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_lineRproduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse> GET_lineRproductAsync(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_completeproductplanResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_completeproductplan", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse Get_completeproductplan(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_completeproductplan", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse> Get_completeproductplanAsync(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_realstockResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_realstock", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse Get_realstock(Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_realstock", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse> Get_realstockAsync(Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_stopplanResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_stopplan", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse Get_stopplan(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_stopplan", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse> Get_stopplanAsync(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Get_takegoodsResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_takegoods", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse Get_takegoods(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_takegoods", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse> Get_takegoodsAsync(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_ALL_ONECE", ReplyAction="*")]
        Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse GET_ALL_ONECE(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_ALL_ONECE", ReplyAction="*")]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse> GET_ALL_ONECEAsync(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_APS_DISPATCHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_APS_DISPATCH", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequestBody Body;
        
        public GET_APS_DISPATCHRequest() {
        }
        
        public GET_APS_DISPATCHRequest(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GET_APS_DISPATCHRequestBody {
        
        public GET_APS_DISPATCHRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_APS_DISPATCHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_APS_DISPATCHResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponseBody Body;
        
        public GET_APS_DISPATCHResponse() {
        }
        
        public GET_APS_DISPATCHResponse(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_APS_DISPATCHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_APS_DISPATCHResult;
        
        public GET_APS_DISPATCHResponseBody() {
        }
        
        public GET_APS_DISPATCHResponseBody(string GET_APS_DISPATCHResult) {
            this.GET_APS_DISPATCHResult = GET_APS_DISPATCHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_OVER_ORDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_OVER_ORDER", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequestBody Body;
        
        public GET_OVER_ORDERRequest() {
        }
        
        public GET_OVER_ORDERRequest(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GET_OVER_ORDERRequestBody {
        
        public GET_OVER_ORDERRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_OVER_ORDERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_OVER_ORDERResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponseBody Body;
        
        public GET_OVER_ORDERResponse() {
        }
        
        public GET_OVER_ORDERResponse(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_OVER_ORDERResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_OVER_ORDERResult;
        
        public GET_OVER_ORDERResponseBody() {
        }
        
        public GET_OVER_ORDERResponseBody(string GET_OVER_ORDERResult) {
            this.GET_OVER_ORDERResult = GET_OVER_ORDERResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_APS_MATERIASETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_APS_MATERIASET", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequestBody Body;
        
        public GET_APS_MATERIASETRequest() {
        }
        
        public GET_APS_MATERIASETRequest(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GET_APS_MATERIASETRequestBody {
        
        public GET_APS_MATERIASETRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_APS_MATERIASETResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_APS_MATERIASETResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponseBody Body;
        
        public GET_APS_MATERIASETResponse() {
        }
        
        public GET_APS_MATERIASETResponse(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_APS_MATERIASETResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_APS_MATERIASETResult;
        
        public GET_APS_MATERIASETResponseBody() {
        }
        
        public GET_APS_MATERIASETResponseBody(string GET_APS_MATERIASETResult) {
            this.GET_APS_MATERIASETResult = GET_APS_MATERIASETResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_materialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_material", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_materialRequestBody Body;
        
        public Get_materialRequest() {
        }
        
        public Get_materialRequest(Zephyr.Areas.ServiceReferenceAPS.Get_materialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_materialRequestBody {
        
        public Get_materialRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_materialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_materialResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_materialResponseBody Body;
        
        public Get_materialResponse() {
        }
        
        public Get_materialResponse(Zephyr.Areas.ServiceReferenceAPS.Get_materialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_materialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_materialResult;
        
        public Get_materialResponseBody() {
        }
        
        public Get_materialResponseBody(string Get_materialResult) {
            this.Get_materialResult = Get_materialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_lineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_line", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_lineRequestBody Body;
        
        public Get_lineRequest() {
        }
        
        public Get_lineRequest(Zephyr.Areas.ServiceReferenceAPS.Get_lineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_lineRequestBody {
        
        public Get_lineRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_lineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_lineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_lineResponseBody Body;
        
        public Get_lineResponse() {
        }
        
        public Get_lineResponse(Zephyr.Areas.ServiceReferenceAPS.Get_lineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_lineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_lineResult;
        
        public Get_lineResponseBody() {
        }
        
        public Get_lineResponseBody(string Get_lineResult) {
            this.Get_lineResult = Get_lineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_technologyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_technology", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequestBody Body;
        
        public Get_technologyRequest() {
        }
        
        public Get_technologyRequest(Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_technologyRequestBody {
        
        public Get_technologyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_technologyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_technologyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponseBody Body;
        
        public Get_technologyResponse() {
        }
        
        public Get_technologyResponse(Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_technologyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_technologyResult;
        
        public Get_technologyResponseBody() {
        }
        
        public Get_technologyResponseBody(string Get_technologyResult) {
            this.Get_technologyResult = Get_technologyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_lineRproductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_lineRproduct", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequestBody Body;
        
        public GET_lineRproductRequest() {
        }
        
        public GET_lineRproductRequest(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GET_lineRproductRequestBody {
        
        public GET_lineRproductRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_lineRproductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_lineRproductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponseBody Body;
        
        public GET_lineRproductResponse() {
        }
        
        public GET_lineRproductResponse(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_lineRproductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_lineRproductResult;
        
        public GET_lineRproductResponseBody() {
        }
        
        public GET_lineRproductResponseBody(string GET_lineRproductResult) {
            this.GET_lineRproductResult = GET_lineRproductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_completeproductplanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_completeproductplan", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequestBody Body;
        
        public Get_completeproductplanRequest() {
        }
        
        public Get_completeproductplanRequest(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_completeproductplanRequestBody {
        
        public Get_completeproductplanRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_completeproductplanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_completeproductplanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponseBody Body;
        
        public Get_completeproductplanResponse() {
        }
        
        public Get_completeproductplanResponse(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_completeproductplanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_completeproductplanResult;
        
        public Get_completeproductplanResponseBody() {
        }
        
        public Get_completeproductplanResponseBody(string Get_completeproductplanResult) {
            this.Get_completeproductplanResult = Get_completeproductplanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_realstockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_realstock", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequestBody Body;
        
        public Get_realstockRequest() {
        }
        
        public Get_realstockRequest(Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_realstockRequestBody {
        
        public Get_realstockRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_realstockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_realstockResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponseBody Body;
        
        public Get_realstockResponse() {
        }
        
        public Get_realstockResponse(Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_realstockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_realstockResult;
        
        public Get_realstockResponseBody() {
        }
        
        public Get_realstockResponseBody(string Get_realstockResult) {
            this.Get_realstockResult = Get_realstockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_stopplanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_stopplan", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequestBody Body;
        
        public Get_stopplanRequest() {
        }
        
        public Get_stopplanRequest(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_stopplanRequestBody {
        
        public Get_stopplanRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_stopplanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_stopplanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponseBody Body;
        
        public Get_stopplanResponse() {
        }
        
        public Get_stopplanResponse(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_stopplanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_stopplanResult;
        
        public Get_stopplanResponseBody() {
        }
        
        public Get_stopplanResponseBody(string Get_stopplanResult) {
            this.Get_stopplanResult = Get_stopplanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_takegoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_takegoods", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequestBody Body;
        
        public Get_takegoodsRequest() {
        }
        
        public Get_takegoodsRequest(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_takegoodsRequestBody {
        
        public Get_takegoodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_takegoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_takegoodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponseBody Body;
        
        public Get_takegoodsResponse() {
        }
        
        public Get_takegoodsResponse(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_takegoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_takegoodsResult;
        
        public Get_takegoodsResponseBody() {
        }
        
        public Get_takegoodsResponseBody(string Get_takegoodsResult) {
            this.Get_takegoodsResult = Get_takegoodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_ALL_ONECERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_ALL_ONECE", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequestBody Body;
        
        public GET_ALL_ONECERequest() {
        }
        
        public GET_ALL_ONECERequest(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_ALL_ONECERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pwd;
        
        public GET_ALL_ONECERequestBody() {
        }
        
        public GET_ALL_ONECERequestBody(string user, int pwd) {
            this.user = user;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_ALL_ONECEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_ALL_ONECEResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponseBody Body;
        
        public GET_ALL_ONECEResponse() {
        }
        
        public GET_ALL_ONECEResponse(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_ALL_ONECEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_ALL_ONECEResult;
        
        public GET_ALL_ONECEResponseBody() {
        }
        
        public GET_ALL_ONECEResponseBody(string GET_ALL_ONECEResult) {
            this.GET_ALL_ONECEResult = GET_ALL_ONECEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Zephyr.Areas.ServiceReferenceAPS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Zephyr.Areas.ServiceReferenceAPS.Service1Soap>, Zephyr.Areas.ServiceReferenceAPS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_APS_DISPATCH(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest request) {
            return base.Channel.GET_APS_DISPATCH(request);
        }
        
        public string GET_APS_DISPATCH() {
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_APS_DISPATCH(inValue);
            return retVal.Body.GET_APS_DISPATCHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_APS_DISPATCHAsync(Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest request) {
            return base.Channel.GET_APS_DISPATCHAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHResponse> GET_APS_DISPATCHAsync() {
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_DISPATCHRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_APS_DISPATCHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_OVER_ORDER(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest request) {
            return base.Channel.GET_OVER_ORDER(request);
        }
        
        public string GET_OVER_ORDER() {
            Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_OVER_ORDER(inValue);
            return retVal.Body.GET_OVER_ORDERResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_OVER_ORDERAsync(Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest request) {
            return base.Channel.GET_OVER_ORDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERResponse> GET_OVER_ORDERAsync() {
            Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_OVER_ORDERRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_OVER_ORDERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_APS_MATERIASET(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest request) {
            return base.Channel.GET_APS_MATERIASET(request);
        }
        
        public string GET_APS_MATERIASET() {
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_APS_MATERIASET(inValue);
            return retVal.Body.GET_APS_MATERIASETResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_APS_MATERIASETAsync(Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest request) {
            return base.Channel.GET_APS_MATERIASETAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETResponse> GET_APS_MATERIASETAsync() {
            Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_APS_MATERIASETRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_APS_MATERIASETAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_material(Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest request) {
            return base.Channel.Get_material(request);
        }
        
        public string Get_material() {
            Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_materialRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_material(inValue);
            return retVal.Body.Get_materialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_materialAsync(Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest request) {
            return base.Channel.Get_materialAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_materialResponse> Get_materialAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_materialRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_materialRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_materialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_line(Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest request) {
            return base.Channel.Get_line(request);
        }
        
        public string Get_line() {
            Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_lineRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_line(inValue);
            return retVal.Body.Get_lineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_lineAsync(Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest request) {
            return base.Channel.Get_lineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_lineResponse> Get_lineAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_lineRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_lineRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_lineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_technology(Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest request) {
            return base.Channel.Get_technology(request);
        }
        
        public string Get_technology() {
            Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_technology(inValue);
            return retVal.Body.Get_technologyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_technologyAsync(Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest request) {
            return base.Channel.Get_technologyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_technologyResponse> Get_technologyAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_technologyRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_technologyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_lineRproduct(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest request) {
            return base.Channel.GET_lineRproduct(request);
        }
        
        public string GET_lineRproduct() {
            Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_lineRproduct(inValue);
            return retVal.Body.GET_lineRproductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_lineRproductAsync(Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest request) {
            return base.Channel.GET_lineRproductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductResponse> GET_lineRproductAsync() {
            Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_lineRproductRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_lineRproductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_completeproductplan(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest request) {
            return base.Channel.Get_completeproductplan(request);
        }
        
        public string Get_completeproductplan() {
            Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_completeproductplan(inValue);
            return retVal.Body.Get_completeproductplanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_completeproductplanAsync(Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest request) {
            return base.Channel.Get_completeproductplanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanResponse> Get_completeproductplanAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_completeproductplanRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_completeproductplanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_realstock(Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest request) {
            return base.Channel.Get_realstock(request);
        }
        
        public string Get_realstock() {
            Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_realstock(inValue);
            return retVal.Body.Get_realstockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_realstockAsync(Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest request) {
            return base.Channel.Get_realstockAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_realstockResponse> Get_realstockAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_realstockRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_realstockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_stopplan(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest request) {
            return base.Channel.Get_stopplan(request);
        }
        
        public string Get_stopplan() {
            Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_stopplan(inValue);
            return retVal.Body.Get_stopplanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_stopplanAsync(Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest request) {
            return base.Channel.Get_stopplanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_stopplanResponse> Get_stopplanAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_stopplanRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_stopplanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_takegoods(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest request) {
            return base.Channel.Get_takegoods(request);
        }
        
        public string Get_takegoods() {
            Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequestBody();
            Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_takegoods(inValue);
            return retVal.Body.Get_takegoodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.Get_takegoodsAsync(Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest request) {
            return base.Channel.Get_takegoodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsResponse> Get_takegoodsAsync() {
            Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest inValue = new Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.Get_takegoodsRequestBody();
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).Get_takegoodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_ALL_ONECE(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest request) {
            return base.Channel.GET_ALL_ONECE(request);
        }
        
        public string GET_ALL_ONECE(string user, int pwd) {
            Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequestBody();
            inValue.Body.user = user;
            inValue.Body.pwd = pwd;
            Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse retVal = ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_ALL_ONECE(inValue);
            return retVal.Body.GET_ALL_ONECEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse> Zephyr.Areas.ServiceReferenceAPS.Service1Soap.GET_ALL_ONECEAsync(Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest request) {
            return base.Channel.GET_ALL_ONECEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECEResponse> GET_ALL_ONECEAsync(string user, int pwd) {
            Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest inValue = new Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequest();
            inValue.Body = new Zephyr.Areas.ServiceReferenceAPS.GET_ALL_ONECERequestBody();
            inValue.Body.user = user;
            inValue.Body.pwd = pwd;
            return ((Zephyr.Areas.ServiceReferenceAPS.Service1Soap)(this)).GET_ALL_ONECEAsync(inValue);
        }
    }
}
